2020-06-14T17:37:58-0300 [-] Creating router ...
2020-06-14T17:37:58-0300 [-] Initializing Router - Number of events: 1
2020-06-14T17:37:59-0300 [-] RouterFactory starting on 8081
2020-06-14T17:37:59-0300 [-] Creating AccessPoint station ...
2020-06-14T17:37:59-0300 [-] Initializing Access Point - Number of events: 2
2020-06-14T17:37:59-0300 [-] There is no wifi devices in this simulation or it is not in this wifi signal coverage area.
2020-06-14T17:38:00-0300 [-] Initializing Server - Number of events: 3
2020-06-14T17:38:00-0300 [-] BrokerFactory starting on 5100
2020-06-14T17:38:00-0300 [-] Initializing Server - Number of events: 4
2020-06-14T17:38:01-0300 [-] DatabaseServerAppFactory starting on 8083
2020-06-14T17:38:01-0300 [-] Initializing Client - Number of events: 5
2020-06-14T17:38:01-0300 [-] Initializing Client - Number of events: 6
2020-06-14T17:38:02-0300 [-] Initializing sink node - Number of events: 7
2020-06-14T17:38:02-0300 [-] Initializing sensor node - Number of events: 8
2020-06-14T17:38:03-0300 [-] Initializing sensor node - Number of events: 9
2020-06-14T17:38:03-0300 [-] Initializing sensor node - Number of events: 10
2020-06-14T17:38:04-0300 [-] Initializing sensor node - Number of events: 11
2020-06-14T17:38:04-0300 [-] Initializing sensor node - Number of events: 12
2020-06-14T17:38:05-0300 [-] Initializing sensor node - Number of events: 13
2020-06-14T17:38:05-0300 [-] Initializing sensor node - Number of events: 14
2020-06-14T17:38:06-0300 [-] Initializing sensor node - Number of events: 15
2020-06-14T17:38:06-0300 [-] Initializing sensor node - Number of events: 16
2020-06-14T17:38:07-0300 [stderr#error] Exception in Tkinter callback
2020-06-14T17:38:07-0300 [stderr#error] Traceback (most recent call last):
2020-06-14T17:38:07-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-06-14T17:38:07-0300 [stderr#error]     return self.func(*args)
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 107, in <lambda>
2020-06-14T17:38:07-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 61, in open_project
2020-06-14T17:38:07-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 204, in load_nodes
2020-06-14T17:38:07-0300 [stderr#error]     deivce.run()
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 269, in run
2020-06-14T17:38:07-0300 [stderr#error]     self.application.start(nearby_devices_list)
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 154, in start
2020-06-14T17:38:07-0300 [stderr#error]     self.connect_to_gateway()
2020-06-14T17:38:07-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 162, in connect_to_gateway
2020-06-14T17:38:07-0300 [stderr#error]     reactor.connectTCP(self.gateway_addr, self.gateway_port, factory)
2020-06-14T17:38:07-0300 [stderr#error] AttributeError: 'SinkApp' object has no attribute 'gateway_addr'
2020-06-14T17:38:07-0300 [stdout#info] This divice have no simulation core instance
2020-06-14T17:38:07-0300 [stdout#info] This divice have no simulation core instance
2020-06-14T17:38:07-0300 [stdout#info] This divice have no simulation core instance
2020-06-14T17:38:07-0300 [stdout#info] This divice have no simulation core instance
2020-06-14T17:38:07-0300 [Uninitialized] 127.0.0.1:57536 - Connected to mqtt broker - Number of events: 17
2020-06-14T17:38:07-0300 [Uninitialized] 127.0.0.1:57536 - sending MQTT SUBSCRIBE REQUEST - Number of events: 18
2020-06-14T17:38:07-0300 [Uninitialized] 127.0.0.1:57538 - Connected to mqtt broker - Number of events: 19
2020-06-14T17:38:07-0300 [Uninitialized] 127.0.0.1:57538 - sending MQTT SUBSCRIBE REQUEST - Number of events: 20
2020-06-14T17:38:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fc993c4dd30>
2020-06-14T17:38:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fc993c4df28>
2020-06-14T17:39:52-0300 [-] Received SIGINT, shutting down.
2020-06-14T17:39:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fc993c4dd30>
2020-06-14T17:39:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7fc993c4df28>
2020-06-14T17:39:52-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-06-14T17:39:52-0300 [SubscriberApp,client] connection lost - Number of events: 21
2020-06-14T17:39:52-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-06-14T17:39:52-0300 [SubscriberApp,client] connection lost - Number of events: 22
2020-06-14T17:39:52-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-14T17:39:52-0300 [applications.databaseserverapp.DatabaseServerAppFactory] (TCP Port 8083 Closed)
2020-06-14T17:39:52-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-06-14T17:39:52-0300 [-] Main loop terminated.
