2021-01-21T16:40:18-0300 [stderr#error] Exception in Tkinter callback
2021-01-21T16:40:18-0300 [stderr#error] Traceback (most recent call last):
2021-01-21T16:40:18-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2021-01-21T16:40:18-0300 [stderr#error]     return self.func(*args)
2021-01-21T16:40:18-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 120, in <lambda>
2021-01-21T16:40:18-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2021-01-21T16:40:18-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 71, in open_project
2021-01-21T16:40:18-0300 [stderr#error]     simulation_core.create_simulation_canvas()
2021-01-21T16:40:18-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/simulationcore.py", line 204, in create_simulation_canvas
2021-01-21T16:40:18-0300 [stderr#error]     self.simulation_screen = ScrollableScreen(window, self.project_name)
2021-01-21T16:40:18-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/ScrollableScreen.py", line 22, in __init__
2021-01-21T16:40:18-0300 [stderr#error]     background_image = PIL.Image.open(bg_image_path)
2021-01-21T16:40:18-0300 [stderr#error]   File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/PIL/Image.py", line 2766, in open
2021-01-21T16:40:18-0300 [stderr#error]     fp = builtins.open(filename, "rb")
2021-01-21T16:40:18-0300 [stderr#error] FileNotFoundError: [Errno 2] No such file or directory: 'projects/simple_wsn_scada/bg_image.png'
2021-01-21T16:40:47-0300 [-] Received SIGINT, shutting down.
2021-01-21T16:40:47-0300 [-] Main loop terminated.
